[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "dna2graph"
version = "1.0.2"
description = """Imaging software that automates the segmentation and analysis of DNA molecules in electron microscopy images (CLI + GUI)."""
authors = [
  { name = "Federico Chinello", email = "federico.chinello@studbocconi.it" }
]
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.11,<3.15"
dependencies = [
  "numpy>=1.24.4",
  "scipy>=1.10.1",
  "scikit-image>=0.21.0",
  "opencv-python>=4.8.0.76",
  "torch>=2.0.1",
  "monai>=1.3.0",
  "pandas>=2.0.3",
  "networkx>=3.1",
  "h5py>=3.8.0",
  "roifile>=2023.5.12",
  "huggingface-hub>=0.20.0",
  "tqdm>=4.65.0",
  "packaging>=23.0",
  "appdirs>=1.4.4",
]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Intended Audience :: Science/Research",
  "Topic :: Scientific/Engineering",
  "Topic :: Scientific/Engineering :: Bio-Informatics",
  "Topic :: Scientific/Engineering :: Image Processing",
  "Topic :: Scientific/Engineering :: Medical Science Apps."
]
keywords = ["DNA", "electron microscopy", "image analysis", "segmentation"]

[project.urls]
Homepage = "https://federicochinello.com/DNA2Graph"
Source = "https://github.com/chinefed/DNA2Graph"
Documentation = "https://federicochinello.com/DNA2Graph"

[project.scripts]
dna2graph-cli = "dna2graph.cli_main:main"
dna2graph = "dna2graph.gui_main:main"

[tool.hatch.build]
include = [
  "dna2graph/**/*.py",
  "dna2graph/assets/defaults.json",
  "dna2graph/assets/target_cdf.npy",
  "dna2graph/assets/logo.ico"
]

[tool.hatch.build.targets.wheel]
packages = ["dna2graph"]